name: clisopsdev
channels:
 - conda-forge
 - defaults
dependencies:
 - pip
 - numpy>=1.16
 - xarray>=0.15
 - pandas>=1.0.3
 - cftime>=1.4.1
 - netCDF4>=1.4
 - poppler>=0.67
 - shapely>=1.6
 - geopandas>=0.7
 - dask>=2.6.0
 - bottleneck>=1.3.1,<1.4
 - pyproj>=2.5
 - requests>=2.0
 - cf_xarray>=0.3.1
 - fiona>=1.8
 - geojson>=2.5.0
 - udunits2>=2.2
 - pywps>=4.4.0,<4.5
 - click
 - psutil
 - rtree>=0.9
 - cfunits
 - networkx
 - prov>=2.0.0
 - graphviz
 - python-dateutil>=2.8.1
 - jinja2
 - elasticsearch>=7.9.1
 - birdy
 - beautifulsoup4
 - oyaml>=0.9
